site_name: Ubiquerg
site_url: http://pep.databio.org/ubiquerg/
repo_url: http://github.com/pepkit/ubiquerg
pypi_name: ubiquerg

nav:
  - Introduction:
    - Home: README.md
  - Reference:
    - API: autodoc_build/ubiquerg.md
    - Support: http://github.com/pepkit/ubiquerg/issues
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio

plugins:
  - databio:
      autodoc_build: "docs/autodoc_build"
      autodoc_package: "ubiquerg"
      no_top_level: true
  - search

